on: [push, pull_request]
name: build

jobs:
  build:
    name: build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        build: [linux, macos, windows]
        include:
          - build: linux
            os: ubuntu-latest
            rust: nightly
            target: x86_64-unknown-linux-musl
            archive-name: pic_game-linux.tar.gz
          - build: macos
            os: macos-latest
            rust: nightly
            target: x86_64-apple-darwin
            archive-name: pic_game-macos.tar.gz
          - build: windows
            os: windows-2019
            rust: nightly-x86_64-msvc
            target: x86_64-pc-windows-msvc
            archive-name: pic_game-windows.7z
      fail-fast: false

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.rust }}
          profile: minimal
          override: true
          target: ${{ matrix.target }}
      
      - name: install openssl-tools
        if: matrix.build == 'linux'
        run: |
          sudo apt-get update
          sudo apt-get install libssl-dev cmake pkg-config musl-tools

      - name: Build binary
        run: |
          cargo build --target ${{ matrix.target }}
          cargo build --release --target ${{ matrix.target }} 
        env:
          RUST_BACKTRACE: 1

      - name: Strip binary (linux and macos)
        if: matrix.build == 'linux' || matrix.build == 'macos'
        run: |
          strip "target/${{ matrix.target }}/debug/pic_game"
          strip "target/${{ matrix.target }}/release/pic_game"

      - name: Build archive
        shell: bash
        run: |
          mkdir archive
          cd archive
          if [ "${{ matrix.build }}" = "windows" ]; then
            cp "../target/${{ matrix.target }}/debug/pic_game.exe" ./
            cp "../target/${{ matrix.target }}/release/pic_game.exe" ./pic_game_release.exe
            cp -r "../static" ./
            cp "../Rocket.toml" ./
            cp -r "../database/" ./
            7z a "${{ matrix.archive-name }}" pic_game.exe pic_game_release.exe static Rocket.toml database
          else
            cp "../target/${{ matrix.target }}/debug/pic_game" ./
            cp "../target/${{ matrix.target }}/release/pic_game" ./pic_game_release
            cp -r "../static" ./
            cp "../Rocket.toml" ./
            cp -r "../database/" ./
            tar -czf "${{ matrix.archive-name }}" pic_game pic_game_release static Rocket.toml database
          fi
      - name: Upload archive
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.archive-name }}
          path: archive/${{ matrix.archive-name }}

  # release:
  #   name: Release
  #   runs-on: ubuntu-latest
  #   if: ${{ startsWith(github.ref, 'refs/heads/main') }}
  #   needs: [build]
  #   permissions:
  #     # Use to sign the release artifacts
  #     id-token: write
  #     # Used to upload release artifacts
  #     contents: write
  #     # Used to generate artifact attestation
  #     attestations: write
  #   steps:
  #     - uses: actions/download-artifact@v4
  #     - name: Display structure of downloaded files
  #       run: ls -R
  #     - name: pwd
  #       run: pwd
  #     # - name: Generate artifact attestation
  #     #   uses: actions/attest-build-provenance@v1
  #     #   with:
  #     #     subject-path: 'wheels-*/*'
  #     - name: Release
  #       uses: softprops/action-gh-release@v2
  #       with:
  #         files: |
  #           /home/runner/work/pic_game/pic_game/pic_game-linux.tar.gz
  #           /home/runner/work/pic_game/pic_game/pic_game-macos.tar.gz
  #           /home/runner/work/pic_game/pic_game/pic_game-windows.7z
  #         draft: true
  #         fail_on_unmatched_files: true